name: Android PR CI

on:
  pull_request:
    branches: [ master ]
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK
      uses: actions/setup-java@v1
      with:
        java-version: 8
      
    - name: "Lint check"
      run: chmod +x gradlew && ./gradlew clean ktlintCheck --no-daemon
      
    - name: "Run Unit Tests"
      run: chmod +x gradlew && ./gradlew clean check
